// <auto-generated />
using System;
using CarrierRates.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarrierRates.Api.Data.Migrations
{
    [DbContext(typeof(CarrierRatesContext))]
    [Migration("20240827102329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CarrierRates.Api.Entities.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DHL",
                            UpdatedAt = new DateOnly(2024, 8, 27),
                            isEnabled = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lalamove",
                            UpdatedAt = new DateOnly(2024, 8, 27),
                            isEnabled = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
